### ISSUE TITLE
Regarding the co-simulation...

### ISSUE THREAD

**Issue by Jctrp** [Dekai21/Multi_Agent_Intersection#2]
Hi! Thanks for this great work!
But I have encountered some problems while implementing the simulation code for this project, and I am unable to simulate the expected results as shown in the video.
![捕获](https://github.com/Dekai21/Multi_Agent_Intersection/assets/91713256/4425d233-aaa3-462c-98a2-427d06a9cd5d)

I am new to joint simulations using SUMO and CARLA, and I would appreciate SOME HELP in this regard! 
Additionllay, I want to konw how to output and compute the online evaluation metrics DCR mentioned in the research paper using CARLA and SUMO.

I look forward to any response on this issue!

**Comment by Dekai21** [comment]
Hi, thanks for your interest. Are you using the trained weights I released? As for the DCR, I calculated it based on the whole travel distance of all vehicles and the manually count collision time.

**Comment by Jctrp** [comment]
Hello, thank you for your response!

My environment versions are: SUMO1.18.0 and CARLA 0.9.12.
I ran the replication experiments on Windows 11.

Using the pre-trained models provided by this project instead of reproducing my own checkpoints has improved the simulation results significantly. However, some issues still persist.

Firstly, I keep encountering an error during the simulation: 'ERROR: failed to destroy actor xx: unable to destroy actor: not found.'    Is this normal? I suspect that this error is causing SUMO to freeze during joint simulation.

Secondly, during the co-simulation, vehicles in SUMO tend to drive out of intersections and get stuck on 'green areas' without disappearing.

Lastly, regarding the calculation of DCR, I noticed the definition and usage of self.odometries in sumo_simulation.py and run_synchronization.py. The line n_collision += collision_detect(x, tgt_agent_ides, dict_collsions, step) appears to be commented out, indicating that the collision detector is not being used in the project.

Additionally, I came across a commented section of code ## Odometry calculation.  I enabled it and computed the output.  However, I added self.odometers_cum = [] before the loop to initialize the list at each time step, otherwise the float type of the previous time step would be used. Should I use this result to calculate DCR?

Based on these summaries, I will continue to study this project until I can reproduce it.  Thank you again for your assistance and this wonderful work!

**Comment by Jctrp** [comment]
I solved the problem 'ERROR: failed to destroy actor xx: unable to destroy actor: not found.' by adding 'self.to_be_destroyed_ids.remove(v).
I enable the Odometry Calculation and obtain the Odometers_cum result 3430.357,  now I am trying to get the collision time and calculate the DCR(V2V) and DCR(V2B).

**Comment by Dekai21** [comment]
thanks again for your huge interest on this project :) for the collision time, as I said, I counted it manually, not sure if carla provides suitable api for this collision detection. For the problem of some cars driving out of the drivable area. I think this could probably due to the lack of robustness of the control model. I tried using the pre-trained model to control the vehicles in a busier and different scenario but the result was not satisfying (I remember many vehicles also ran out of the road). Overall, I think this project is just an exploration about the co-simulation between carla and sumo.

**Comment by Jctrp** [comment]
Thank you for your response.  I'm interested in learning how to run a deep learning-based trajectory prediction model for online evaluation, and this project has taught me a lot.  Now, I can generate my own synthetic dataset in SUMO and use the provided linear model for predicting control actions to process the dataset and test the model's robustness.  Finally, I plan to evaluate the overall performance of the prediction-planning control process in CARLA.  I will use the output 'Odometers_cum' from the 'Odometry calculation' loop as the total distance traveled and manually calculate vehicle-to-vehicle and vehicle-to-road collisions.  I will stop the simulation at 4 minutes (sumo_time > 241).

Once again, thank you for your work.  It has truly been a great learning experience for me!

**Comment by ShenZC25** [comment]
> I solved the problem 'ERROR: failed to destroy actor xx: unable to destroy actor: not found.' by adding 'self.to_be_destroyed_ids.remove(v). I enable the Odometry Calculation and obtain the Odometers_cum result 3430.357, now I am trying to get the collision time and calculate the DCR(V2V) and DCR(V2B).


In addition, I also reported the following errors at the end.

INFO: Cleaning synchronization
Traceback (most recent call last):
  File "run_synchronization.py", line 308, in synchronization_loop
    synchronization.tick()
  File "run_synchronization.py", line 117, in tick
    self.sumo.tick()
  File "F:\CARLA_0.9.10\WindowsNoEditor\Co-Simulation\Sumo\sumo_integration\sumo_simulation.py", line 532, in tick
    traci.simulationStep()
  File "F:\Program Files\Eclipse\Sumo\tools\traci\main.py", line 207, in simulationStep
    return _connections[""].simulationStep(step)
  File "F:\Program Files\Eclipse\Sumo\tools\traci\connection.py", line 323, in simulationStep
    result = self._sendCmd(tc.CMD_SIMSTEP, None, None, "D", step)
  File "F:\Program Files\Eclipse\Sumo\tools\traci\connection.py", line 185, in _sendCmd
    return self._sendExact()
  File "F:\Program Files\Eclipse\Sumo\tools\traci\connection.py", line 95, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO

During handling of the above exception, another exception occurred:

  File "F:\Program Files\Eclipse\Sumo\tools\traci\connection.py", line 323, in simulationStep
    result = self._sendCmd(tc.CMD_SIMSTEP, None, None, "D", step)
  File "F:\Program Files\Eclipse\Sumo\tools\traci\connection.py", line 185, in _sendCmd
    return self._sendExact()
  File "F:\Program Files\Eclipse\Sumo\tools\traci\connection.py", line 83, in _sendExact
    if self._socket is None:
AttributeError: 'Connection' object has no attribute '_socket'
